pipeline {
    agent { label 'master' }
    stages {
        stage('Running unittests') {
            agent { docker { image 'python:2.7-slim-jessie'
                     args '-u root:root' } }
            steps {
                checkout scm
                sh ''' pip install --user cherrypy
                      cd testing/unittests/
                      ./run.sh'''
            }
        }
    }
}
